name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        wget https://github.com/ton-blockchain/ton/releases/download/v2023.06/fift-linux-x86_64
        wget https://raw.githubusercontent.com/ton-blockchain/ton/v2023.06/crypto/fift/lib/Fift.fif
        wget https://raw.githubusercontent.com/ton-blockchain/ton/v2023.06/crypto/fift/lib/Asm.fif
        wget https://raw.githubusercontent.com/ton-blockchain/ton/v2023.06/crypto/fift/lib/GetOpt.fif
        wget https://raw.githubusercontent.com/ton-blockchain/ton/v2023.06/crypto/fift/lib/TonUtil.fif

        mv ./fift-linux-x86_64 fift /usr/local/bin/fift
        chmod +x /usr/local/bin/fift
    - run: make test
