name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: |
        wget $REPOSITORY/releases/download/$VERSION/fift-linux-x86_64
        wget $REPOSITORY/$VERSION/crypto/fift/lib/Fift.fif
        wget $REPOSITORY/$VERSION/crypto/fift/lib/Asm.fif
        wget $REPOSITORY/$VERSION/crypto/fift/lib/GetOpt.fif
        wget $REPOSITORY/$VERSION/crypto/fift/lib/TonUtil.fif
        mv ./fift-linux-x86_64 /usr/local/bin/fift
        chmod +x /usr/bin/fift
      env:
        REPOSITORY: https://github.com/ton-blockchain/ton
        VERSION: v2023.06
    - run: make test